apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: PostgreSql
    plural: postgresqls
    shortNames:
    - pg
    singular: postgresql
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  encryption:
                    type: boolean
                  version:
                    enum:
                    - 15
                    - 14
                    - 13
                    - 12
                    - 11
                    type: integer
                required:
                - encryption
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: PostgreSql
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: Redis
    plural: redis
    shortNames:
    - r
    singular: redis
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  encryption:
                    type: boolean
                  version:
                    enum:
                    - 626
                    type: integer
                required:
                - encryption
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: Redis
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: MySql
    plural: mysqls
    shortNames:
    - my
    singular: mysql
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  encryption:
                    type: boolean
                  version:
                    enum:
                    - 57
                    - 80
                    type: integer
                required:
                - encryption
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: MySql
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongodbs.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: MongoDb
    plural: mongodbs
    shortNames:
    - mo
    singular: mongodb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  encryption:
                    type: boolean
                  version:
                    enum:
                    - 403
                    type: integer
                required:
                - encryption
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: MongoDb
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pulsars.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: Pulsar
    plural: pulsars
    shortNames:
    - pulse
    - pul
    singular: pulsar
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  region:
                    type: string
                required:
                - region
                type: object
              organisation:
                type: string
            required:
            - instance
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: Pulsar
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configproviders.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: ConfigProvider
    plural: configproviders
    shortNames:
    - cp
    singular: configprovider
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              organisation:
                type: string
              variables:
                additionalProperties:
                  type: string
                type: object
            required:
            - organisation
            - variables
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: ConfigProvider
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: elasticsearches.api.clever-cloud.com
spec:
  group: api.clever-cloud.com
  names:
    categories: []
    kind: ElasticSearch
    plural: elasticsearches
    shortNames:
    - es
    singular: elasticsearch
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Organisation
      jsonPath: .spec.organisation
      name: organisation
      type: string
    - description: Addon
      jsonPath: .status.addon
      name: addon
      type: string
    - description: Region
      jsonPath: .spec.instance.region
      name: region
      type: string
    - description: Instance
      jsonPath: .spec.instance.plan
      name: instance
      type: string
    - description: Version
      jsonPath: .spec.options.version
      name: version
      type: integer
    - description: Cold encryption
      jsonPath: .spec.options.encryption
      name: encrypted
      type: boolean
    - description: Kibana
      jsonPath: .spec.options.kibana
      name: kibana
      type: boolean
    - description: Application Perfomance Monitoring
      jsonPath: .spec.options.apm
      name: apm
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for Spec via `CustomResource`
        properties:
          spec:
            properties:
              instance:
                properties:
                  plan:
                    type: string
                  region:
                    type: string
                required:
                - plan
                - region
                type: object
              options:
                properties:
                  apm:
                    type: boolean
                  encryption:
                    type: boolean
                  kibana:
                    type: boolean
                  version:
                    enum:
                    - 6
                    - 7
                    type: integer
                required:
                - apm
                - encryption
                - kibana
                - version
                type: object
              organisation:
                type: string
            required:
            - instance
            - options
            - organisation
            type: object
          status:
            nullable: true
            properties:
              addon:
                nullable: true
                type: string
            type: object
        required:
        - spec
        title: ElasticSearch
        type: object
    served: true
    storage: true
    subresources:
      status: {}
