# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "clever-operator"
description = "A kubernetes operator that expose clever cloud's resources through custom resource definition"
version = "0.1.0"
edition = "2018"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
keywords = ["kubernetes", "operator", "clevercloud"]

[dependencies]
async-trait = "^0.1.51"
base64 = "^0.13.0"
bytes = { version = "^1.1.0", features = ["serde"] }
chrono = "^0.4.19"
config = "^0.11.0"
futures = "^0.3.17"
hostname = "^0.3.1"
hmac = { version = "^0.11.0", features = ["std"] }
hyper = { version = "^0.14.13", features = ["client", "server", "tcp", "http1", "http2", "stream", "runtime"] }
hyper-tls = "^0.5.0"
json-patch = "^0.2.6"
kube = { version = "^0.61.0", default-features = false, features = ["client", "rustls-tls", "ws", "gzip", "derive", "jsonpatch"] }
kube-derive = "^0.61.0"
kube-runtime = "^0.61.0"
k8s-openapi = { version = "^0.13.0", default-features = false, features = ["v1_21"] }
lazy_static = "^1.4.0"
paw = "^1.0.0"
prometheus = "^0.13.0"
schemars = { version = "^0.8.6", features = [ "chrono", "indexmap", "uuid", "bytes", "url" ] }
serde = { version = "^1.0.130", features = ["derive"] }
serde_json = { version = "^1.0.68", features = ["preserve_order", "float_roundtrip"] }
serde_repr = "^0.1.7"
serde_yaml = "^0.8.21"
sha2 = "^0.9.6"
slog = { version = "^2.7.0", features = ["release_max_level_debug", "max_level_debug"] }
slog-async = "^2.7.0"
slog-term = "^2.8.0"
slog-scope = "^4.4.0"
slog-stdlog = "^4.1.0"
structopt = { version = "^0.3.23", features = ["paw"] }
thiserror = "^1.0.29"
tokio = { version = "^1.12.0", features = ["full"] }
urlencoding = "^2.1.0"
uuid = { version = "^0.8.2", features = ["serde", "v4"] }
