# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "clever-operator"
description = "A kubernetes operator that expose clever cloud's resources through custom resource definition"
version = "0.5.3"
edition = "2021"
rust-version = "1.60.0"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
repository = "https://github.com/CleverCloud/clever-operator"
readme = "README.md"
keywords = ["kubernetes", "operator", "clevercloud", "openshift"]

[dependencies]
async-trait = "^0.1.56"
chrono = "^0.4.19"
clap = { version = "^3.2.10", features = ["derive"] }
clevercloud-sdk = { version = "^0.10.5", features = ["jsonschemas"] }
config = "^0.13.1"
futures = "^0.3.21"
hostname = "^0.3.1"
hyper = { version = "^0.14.20", features = ["server", "tcp", "http1"] }
json-patch = "^0.2.6"
kube = { version = "^0.74.0", default-features = false, features = [
    "client",
    "rustls-tls",
    "ws",
    "gzip",
    "derive",
    "jsonpatch",
] }
kube-derive = "^0.74.0"
kube-runtime = "^0.74.0"
k8s-openapi = { version = "^0.15.0", default-features = false, features = [
    "v1_21",
] }
lazy_static = { version = "^1.4.0", optional = true }
opentelemetry = { version = "^0.17.0", features = [
    "rt-tokio",
], optional = true }
opentelemetry-jaeger = { version = "^0.16.0", features = [
    "rt-tokio",
    "collector_client",
], optional = true }
paw = "^1.0.0"
prometheus = { version = "^0.13.1", optional = true }
schemars = { version = "^0.8.10", features = [
    "chrono",
    "indexmap1",
    "uuid1",
    "bytes",
    "url",
] }
sentry = { version = "^0.27.0", optional = true }
serde = { version = "^1.0.139", features = ["derive"] }
serde_json = { version = "^1.0.82", features = [
    "preserve_order",
    "float_roundtrip",
] }
serde_yaml = "^0.8.25"
thiserror = "^1.0.31"
tokio = { version = "^1.19.2", features = ["full"] }
tracing = "^0.1.35"
tracing-subscriber = { version = "^0.3.14", default-features = false, features = ["std", "ansi", "tracing-log"] }
tracing-opentelemetry = { version = "^0.17.4", optional = true }

[features]
default = [
    "metrics",
    "trace",
    "tracker",
]
logging = [
    "clevercloud-sdk/logging",
]
metrics = ["clevercloud-sdk/metrics", "lazy_static", "prometheus"]
tracker = ["sentry"]
trace = [
    "clevercloud-sdk/trace",
    "clevercloud-sdk/tokio",
    "tracing-opentelemetry",
    "opentelemetry",
    "opentelemetry-jaeger",
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
