# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "clever-operator"
description = "A kubernetes operator that expose clever cloud's resources through custom resource definition"
version = "0.5.1"
edition = "2021"
rust-version = "1.60.0"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
repository = "https://github.com/CleverCloud/clever-operator"
readme = "README.md"
keywords = ["kubernetes", "operator", "clevercloud", "openshift"]

[dependencies]
async-trait = "^0.1.53"
chrono = "^0.4.19"
clap = { version = "^3.1.18", features = ["derive"] }
clevercloud-sdk = { version = "^0.10.2", features = ["jsonschemas"] }
config = "^0.13.1"
futures = "^0.3.21"
hostname = "^0.3.1"
hyper = { version = "^0.14.18", features = ["server", "tcp", "http1"] }
json-patch = "^0.2.6"
kube = { version = "^0.73.0", default-features = false, features = [
    "client",
    "rustls-tls",
    "ws",
    "gzip",
    "derive",
    "jsonpatch",
] }
kube-derive = "^0.73.0"
kube-runtime = "^0.73.0"
k8s-openapi = { version = "^0.15.0", default-features = false, features = [
    "v1_21",
] }
lazy_static = { version = "^1.4.0", optional = true }
opentelemetry = { version = "^0.17.0", features = [
    "rt-tokio",
], optional = true }
opentelemetry-jaeger = { version = "^0.16.0", features = [
    "rt-tokio",
    "collector_client",
], optional = true }
paw = "^1.0.0"
prometheus = { version = "^0.13.1", optional = true }
schemars = { version = "^0.8.10", features = [
    "chrono",
    "indexmap1",
    "uuid1",
    "bytes",
    "url",
] }
sentry = { version = "^0.26.0", optional = true }
serde = { version = "^1.0.137", features = ["derive"] }
serde_json = { version = "^1.0.81", features = [
    "preserve_order",
    "float_roundtrip",
] }
serde_yaml = "^0.8.24"
slog = { version = "^2.7.0" }
slog-async = "^2.7.0"
slog-term = "^2.9.0"
slog-scope = "^4.4.0"
slog-stdlog = { version = "^4.1.1", optional = true }
thiserror = "^1.0.31"
tokio = { version = "^1.18.2", features = ["full"] }
tracing = { version = "^0.1.34", optional = true }
tracing-subscriber = { version = "^0.3.11", optional = true }
tracing-opentelemetry = { version = "^0.17.2", optional = true }

[features]
default = [
    "metrics",
    "trace",
    "tracker",
    "slog/release_max_level_debug",
    "slog/max_level_trace",
]
logging = [
    "clevercloud-sdk/logging",
    "tracing-subscriber/tracing-log",
    "slog-stdlog",
]
metrics = ["clevercloud-sdk/metrics", "lazy_static", "prometheus"]
tracker = ["sentry"]
trace = [
    "clevercloud-sdk/trace",
    "clevercloud-sdk/tokio",
    "tracing",
    "tracing-subscriber",
    "tracing-opentelemetry",
    "opentelemetry",
    "opentelemetry-jaeger",
]
