# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "clever-operator"
description = "A kubernetes operator that expose clever cloud's resources through custom resource definition"
version = "0.1.0"
edition = "2018"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
keywords = ["kubernetes", "operator", "clevercloud"]

[dependencies]
async-trait = "^0.1.51"
bytes = { version = "^1.0.1", features = ["serde"] }
config = "^0.11.0"
hyper = { version = "^0.14.11", features = ["client", "tcp", "http1", "http2", "stream", "runtime"] }
hyper-tls = "^0.5.0"
kube = { version = "^0.59.0", default-features = false, features = ["client", "rustls-tls", "ws", "gzip", "derive", "jsonpatch"] }
kube-runtime = "^0.59.0"
k8s-openapi = { version = "^0.13.0", features = ["v1_21"] }
paw = "^1.0.0"
serde = { version = "^1.0.129", features = ["derive"] }
serde_json = { version = "^1.0.66", features = ["preserve_order", "float_roundtrip"] }
serde_yaml = "^0.8.19"
slog = { version = "^2.7.0", features = ["release_max_level_trace", "max_level_trace"] }
slog-async = "^2.7.0"
slog-term = "^2.8.0"
slog-scope = "^4.4.0"
structopt = { version = "^0.3.22", features = ["paw"] }
tokio = { version = "^1.10.0", features = ["full"] }
thiserror = "^1.0.26"
