apiVersion: v2
name: clever-kubernetes-operator
description: A kubernetes operator that expose clever cloud's resources through custom resource definition
type: application
version: 0.3.0
appVersion: "0.7.0"
