---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: clever-kubernetes-operator
  name: system:clever-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:clever-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: clever-kubernetes-operator
{{ include "cleveroperator.namespace" . | indent 2 }}
