---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: clever-operator
  name: system:clever-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - api.clever-cloud.com
  resources:
  - pulsars
  - pulsars/status
  - mysqls
  - mysqls/status
  - postgresqls
  - postgresqls/status
  - redis
  - redis/status
  - mongodbs
  - mongodbs/status
  - configproviders
  - configproviders/status
  - elasticsearches
  - elasticsearches/status
  - kv
  - kv/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
