{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clever-kubernetes-operator
{{ include "cleveroperator.namespace" . | indent 2 }}
spec:
  podSelector:
    matchLabels:
      app: clever-kubernetes-operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{ toYaml .Values.networkPolicy.ingress | indent 4 }}
  egress:
{{ toYaml .Values.networkPolicy.egress | indent 4 }}
{{- end }}
