{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: clever-kubernetes-operator
  name: clever-kubernetes-operator
{{ include "cleveroperator.namespace" . | indent 2 }}
{{- end }}
