---
apiVersion: api.clever-cloud.com/v1
kind: Redis
metadata:
  namespace: default
  name: redis
spec:
  organisation: orga_<uuid v4>
  options:
    version: 626
    encryption: false
  instance:
    region: par
    plan: s_mono
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-redis
  name: debian-redis
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-redis
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-redis
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-redis
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-redis
  labels:
    app: debian-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-redis
  template:
    metadata:
      labels:
        app: debian-redis
    spec:
      serviceAccountName: debian-redis
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-redis
          command:
            - "sleep"
            - "3600"
          env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-secrets # build using the name of the addon following by -secrets
                key: REDIS_HOST
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_PASSWORD
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_PORT
          - name: REDIS_TOKEN
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_TOKEN
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_URL
          - name: REDIS_VERSION
            valueFrom:
              secretKeyRef:
                name: redis-secrets
                key: REDIS_VERSION
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
